<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->delete();
		$countries = [
            ['name' => 'United States', 'timezone' => 'America/New_York'],
            ['name' => 'Canada', 'timezone' => 'America/Toronto'],
            ['name' => 'Afghanistan', 'timezone' => 'Asia/Kabul'],
            ['name' => 'Albania', 'timezone' => 'Europe/Tirane'],
            ['name' => 'Algeria', 'timezone' => 'Africa/Algiers'],
            ['name' => 'American Samoa', 'timezone' => 'Pacific/Pago_Pago'],
            ['name' => 'Andorra', 'timezone' => 'Europe/Andorra'],
            ['name' => 'Angola', 'timezone' => 'Africa/Luanda'],
            ['name' => 'Anguilla', 'timezone' => 'America/Anguilla'],
            ['name' => 'Antarctica', 'timezone' => 'Antarctica/Palmer'],
            ['name' => 'Antigua and/or Barbuda', 'timezone' => 'America/Antigua'],
            ['name' => 'Argentina', 'timezone' => 'America/Argentina/Buenos_Aires'],
            ['name' => 'Armenia', 'timezone' => 'Asia/Yerevan'],
            ['name' => 'Aruba', 'timezone' => 'America/Aruba'],
            ['name' => 'Australia', 'timezone' => 'Australia/Sydney'],
            ['name' => 'Austria', 'timezone' => 'Europe/Vienna'],
            ['name' => 'Azerbaijan', 'timezone' => 'Asia/Baku'],
            ['name' => 'Bahamas', 'timezone' => 'America/Nassau'],
            ['name' => 'Bahrain', 'timezone' => 'Asia/Bahrain'],
            ['name' => 'Bangladesh', 'timezone' => 'Asia/Dhaka'],
            ['name' => 'Barbados', 'timezone' => 'America/Barbados'],
            ['name' => 'Belarus', 'timezone' => 'Europe/Minsk'],
            ['name' => 'Belgium', 'timezone' => 'Europe/Brussels'],
            ['name' => 'Belize', 'timezone' => 'America/Belize'],
            ['name' => 'Benin', 'timezone' => 'Africa/Porto-Novo'],
            ['name' => 'Bermuda', 'timezone' => 'Atlantic/Bermuda'],
            ['name' => 'Bhutan', 'timezone' => 'Asia/Thimphu'],
            ['name' => 'Bolivia', 'timezone' => 'America/La_Paz'],
            ['name' => 'Bosnia and Herzegovina', 'timezone' => 'Europe/Sarajevo'],
            ['name' => 'Botswana', 'timezone' => 'Africa/Gaborone'],
            ['name' => 'Bouvet Island', 'timezone' => 'Africa/Abidjan'],
            ['name' => 'Brazil', 'timezone' => 'America/Sao_Paulo'],
            ['name' => 'British Indian Ocean Territory', 'timezone' => 'Indian/Chagos'],
            ['name' => 'Brunei Darussalam', 'timezone' => 'Asia/Brunei'],
            ['name' => 'Bulgaria', 'timezone' => 'Europe/Sofia'],
            ['name' => 'Burkina Faso', 'timezone' => 'Africa/Ouagadougou'],
            ['name' => 'Burundi', 'timezone' => 'Africa/Bujumbura'],
            ['name' => 'Cambodia', 'timezone' => 'Asia/Phnom_Penh'],
            ['name' => 'Cameroon', 'timezone' => 'Africa/Douala'],
            ['name' => 'Cape Verde', 'timezone' => 'Atlantic/Cape_Verde'],
            ['name' => 'Cayman Islands', 'timezone' => 'America/Cayman'],
            ['name' => 'Central African Republic', 'timezone' => 'Africa/Bangui'],
            ['name' => 'Chad', 'timezone' => 'Africa/Ndjamena'],
            ['name' => 'Chile', 'timezone' => 'America/Santiago'],
            ['name' => 'China', 'timezone' => 'Asia/Shanghai'],
            ['name' => 'Christmas Island', 'timezone' => 'Indian/Christmas'],
            ['name' => 'Cocos (Keeling) Islands', 'timezone' => 'Indian/Cocos'],
            ['name' => 'Colombia', 'timezone' => 'America/Bogota'],
            ['name' => 'Comoros', 'timezone' => 'Indian/Comoros'],
            ['name' => 'Congo', 'timezone' => 'Africa/Brazzaville'],
            ['name' => 'Cook Islands', 'timezone' => 'Pacific/Rarotonga'],
            ['name' => 'Costa Rica', 'timezone' => 'America/Costa_Rica'],
            ['name' => 'Croatia (Hrvatska)', 'timezone' => 'Europe/Zagreb'],
            ['name' => 'Cuba', 'timezone' => 'America/Havana'],
            ['name' => 'Cyprus', 'timezone' => 'Asia/Nicosia'],
            ['name' => 'Czech Republic', 'timezone' => 'Europe/Prague'],
            ['name' => 'Democratic Republic of Congo', 'timezone' => 'Africa/Kinshasa'],
            ['name' => 'Denmark', 'timezone' => 'Europe/Copenhagen'],
            ['name' => 'Djibouti', 'timezone' => 'Africa/Djibouti'],
            ['name' => 'Dominica', 'timezone' => 'America/Dominica'],
            ['name' => 'Dominican Republic', 'timezone' => 'America/Santo_Domingo'],
            ['name' => 'East Timor', 'timezone' => 'Asia/Dili'],
            ['name' => 'Ecuador', 'timezone' => 'America/Guayaquil'],
            ['name' => 'Egypt', 'timezone' => 'Africa/Cairo'],
            ['name' => 'El Salvador', 'timezone' => 'America/El_Salvador'],
            ['name' => 'Equatorial Guinea', 'timezone' => 'Africa/Malabo'],
            ['name' => 'Eritrea', 'timezone' => 'Africa/Asmara'],
            ['name' => 'Estonia', 'timezone' => 'Europe/Tallinn'],
            ['name' => 'Ethiopia', 'timezone' => 'Africa/Addis_Ababa'],
            ['name' => 'Falkland Islands (Malvinas)', 'timezone' => 'Atlantic/Stanley'],
            ['name' => 'Faroe Islands', 'timezone' => 'Atlantic/Faeroe'],
            ['name' => 'Fiji', 'timezone' => 'Pacific/Fiji'],
            ['name' => 'Finland', 'timezone' => 'Europe/Helsinki'],
            ['name' => 'France', 'timezone' => 'Europe/Paris'],
            ['name' => 'France, Metropolitan', 'timezone' => 'Europe/Paris'],
            ['name' => 'French Guiana', 'timezone' => 'America/Cayenne'],
            ['name' => 'French Polynesia', 'timezone' => 'Pacific/Tahiti'],
            ['name' => 'French Southern Territories', 'timezone' => 'Indian/Kerguelen'],
            ['name' => 'Gabon', 'timezone' => 'Africa/Libreville'],
            ['name' => 'Gambia', 'timezone' => 'Africa/Banjul'],
            ['name' => 'Georgia', 'timezone' => 'Asia/Tbilisi'],
            ['name' => 'Germany', 'timezone' => 'Europe/Berlin'],
            ['name' => 'Ghana', 'timezone' => 'Africa/Accra'],
            ['name' => 'Gibraltar', 'timezone' => 'Europe/Gibraltar'],
            ['name' => 'Greece', 'timezone' => 'Europe/Athens'],
            ['name' => 'Greenland', 'timezone' => 'America/Nuuk'],
            ['name' => 'Grenada', 'timezone' => 'America/Grenada'],
            ['name' => 'Guadeloupe', 'timezone' => 'America/Guadeloupe'],
            ['name' => 'Guam', 'timezone' => 'Pacific/Guam'],
            ['name' => 'Guatemala', 'timezone' => 'America/Guatemala'],
            ['name' => 'Guinea', 'timezone' => 'Africa/Conakry'],
            ['name' => 'Guinea-Bissau', 'timezone' => 'Africa/Bissau'],
            ['name' => 'Guyana', 'timezone' => 'America/Guyana'],
            ['name' => 'Haiti', 'timezone' => 'America/Port-au-Prince'],
            ['name' => 'Heard and Mc Donald Islands', 'timezone' => 'Australia/Perth'],
            ['name' => 'Honduras', 'timezone' => 'America/Tegucigalpa'],
            ['name' => 'Hong Kong', 'timezone' => 'Asia/Hong_Kong'],
            ['name' => 'Hungary', 'timezone' => 'Europe/Budapest'],
            ['name' => 'Iceland', 'timezone' => 'Atlantic/Reykjavik'],
            ['name' => 'India', 'timezone' => 'Asia/Kolkata'],
            ['name' => 'Indonesia', 'timezone' => 'Asia/Jakarta'],
            ['name' => 'Iran (Islamic Republic of)', 'timezone' => 'Asia/Tehran'],
            ['name' => 'Iraq', 'timezone' => 'Asia/Baghdad'],
            ['name' => 'Ireland', 'timezone' => 'Europe/Dublin'],
            ['name' => 'Israel', 'timezone' => 'Asia/Jerusalem'],
            ['name' => 'Italy', 'timezone' => 'Europe/Rome'],
            ['name' => 'Jamaica', 'timezone' => 'America/Jamaica'],
            ['name' => 'Japan', 'timezone' => 'Asia/Tokyo'],
            ['name' => 'Jordan', 'timezone' => 'Asia/Amman'],
            ['name' => 'Kazakhstan', 'timezone' => 'Asia/Almaty'],
            ['name' => 'Kenya', 'timezone' => 'Africa/Nairobi'],
            ['name' => 'Kiribati', 'timezone' => 'Pacific/Tarawa'],
            ['name' => 'Korea (Democratic People\'s Republic of)', 'timezone' => 'Asia/Pyongyang'],
            ['name' => 'Korea (Republic of)', 'timezone' => 'Asia/Seoul'],
            ['name' => 'Kuwait', 'timezone' => 'Asia/Kuwait'],
            ['name' => 'Kyrgyzstan', 'timezone' => 'Asia/Bishkek'],
            ['name' => 'Lao People\'s Democratic Republic', 'timezone' => 'Asia/Vientiane'],
            ['name' => 'Latvia', 'timezone' => 'Europe/Riga'],
            ['name' => 'Lebanon', 'timezone' => 'Asia/Beirut'],
            ['name' => 'Lesotho', 'timezone' => 'Africa/Maseru'],
            ['name' => 'Liberia', 'timezone' => 'Africa/Monrovia'],
            ['name' => 'Libya', 'timezone' => 'Africa/Tripoli'],
            ['name' => 'Liechtenstein', 'timezone' => 'Europe/Vaduz'],
            ['name' => 'Lithuania', 'timezone' => 'Europe/Vilnius'],
            ['name' => 'Luxembourg', 'timezone' => 'Europe/Luxembourg'],
            ['name' => 'Macao', 'timezone' => 'Asia/Macau'],
            ['name' => 'Madagascar', 'timezone' => 'Indian/Antananarivo'],
            ['name' => 'Malawi', 'timezone' => 'Africa/Blantyre'],
            ['name' => 'Malaysia', 'timezone' => 'Asia/Kuala_Lumpur'],
            ['name' => 'Maldives', 'timezone' => 'Indian/Maldives'],
            ['name' => 'Mali', 'timezone' => 'Africa/Bamako'],
            ['name' => 'Malta', 'timezone' => 'Europe/Malta'],
            ['name' => 'Marshall Islands', 'timezone' => 'Pacific/Majuro'],
            ['name' => 'Martinique', 'timezone' => 'America/Martinique'],
            ['name' => 'Mauritania', 'timezone' => 'Africa/Nouakchott'],
            ['name' => 'Mauritius', 'timezone' => 'Indian/Mauritius'],
            ['name' => 'Mayotte', 'timezone' => 'Indian/Mayotte'],
            ['name' => 'Mexico', 'timezone' => 'America/Mexico_City'],
            ['name' => 'Micronesia (Federated States of)', 'timezone' => 'Pacific/Chuuk'],
            ['name' => 'Moldova (Republic of)', 'timezone' => 'Europe/Chisinau'],
            ['name' => 'Monaco', 'timezone' => 'Europe/Monaco'],
            ['name' => 'Mongolia', 'timezone' => 'Asia/Ulaanbaatar'],
            ['name' => 'Montenegro', 'timezone' => 'Europe/Podgorica'],
            ['name' => 'Montserrat', 'timezone' => 'America/Montserrat'],
            ['name' => 'Morocco', 'timezone' => 'Africa/Casablanca'],
            ['name' => 'Mozambique', 'timezone' => 'Africa/Maputo'],
            ['name' => 'Myanmar', 'timezone' => 'Asia/Yangon'],
            ['name' => 'Namibia', 'timezone' => 'Africa/Windhoek'],
            ['name' => 'Nauru', 'timezone' => 'Pacific/Nauru'],
            ['name' => 'Nepal', 'timezone' => 'Asia/Kathmandu'],
            ['name' => 'Netherlands', 'timezone' => 'Europe/Amsterdam'],
            ['name' => 'Netherlands Antilles', 'timezone' => 'America/Curacao'],
            ['name' => 'New Caledonia', 'timezone' => 'Pacific/Noumea'],
            ['name' => 'New Zealand', 'timezone' => 'Pacific/Auckland'],
            ['name' => 'Nicaragua', 'timezone' => 'America/Managua'],
            ['name' => 'Niger', 'timezone' => 'Africa/Niamey'],
            ['name' => 'Nigeria', 'timezone' => 'Africa/Lagos'],
            ['name' => 'Niue', 'timezone' => 'Pacific/Niue'],
            ['name' => 'Norfolk Island', 'timezone' => 'Pacific/Norfolk'],
            ['name' => 'North Macedonia', 'timezone' => 'Europe/Skopje'],
            ['name' => 'Northern Mariana Islands', 'timezone' => 'Pacific/Saipan'],
            ['name' => 'Norway', 'timezone' => 'Europe/Oslo'],
            ['name' => 'Oman', 'timezone' => 'Asia/Muscat'],
            ['name' => 'Pakistan', 'timezone' => 'Asia/Karachi'],
            ['name' => 'Palau', 'timezone' => 'Pacific/Palau'],
            ['name' => 'Palestine', 'timezone' => 'Asia/Gaza'],
            ['name' => 'Panama', 'timezone' => 'America/Panama'],
            ['name' => 'Papua New Guinea', 'timezone' => 'Pacific/Port_Moresby'],
            ['name' => 'Paraguay', 'timezone' => 'America/Asuncion'],
            ['name' => 'Peru', 'timezone' => 'America/Lima'],
            ['name' => 'Philippines', 'timezone' => 'Asia/Manila'],
            ['name' => 'Pitcairn', 'timezone' => 'Pacific/Pitcairn'],
            ['name' => 'Poland', 'timezone' => 'Europe/Warsaw'],
            ['name' => 'Portugal', 'timezone' => 'Europe/Lisbon'],
            ['name' => 'Puerto Rico', 'timezone' => 'America/Puerto_Rico'],
            ['name' => 'Qatar', 'timezone' => 'Asia/Qatar'],
            ['name' => 'Romania', 'timezone' => 'Europe/Bucharest'],
            ['name' => 'Russian Federation', 'timezone' => 'Europe/Moscow'],
            ['name' => 'Rwanda', 'timezone' => 'Africa/Kigali'],
            ['name' => 'Réunion', 'timezone' => 'Indian/Reunion'],
            ['name' => 'Saint Barthelemy', 'timezone' => 'America/St_Barthelemy'],
            ['name' => 'Saint Helena', 'timezone' => 'Atlantic/St_Helena'],
            ['name' => 'Saint Kitts and Nevis', 'timezone' => 'America/St_Kitts'],
            ['name' => 'Saint Lucia', 'timezone' => 'America/St_Lucia'],
            ['name' => 'Saint Martin (French part)', 'timezone' => 'America/Marigot'],
            ['name' => 'Saint Pierre and Miquelon', 'timezone' => 'America/Miquelon'],
            ['name' => 'Saint Vincent and the Grenadines', 'timezone' => 'America/St_Vincent'],
            ['name' => 'Samoa', 'timezone' => 'Pacific/Apia'],
            ['name' => 'San Marino', 'timezone' => 'Europe/San_Marino'],
            ['name' => 'Sao Tome and Principe', 'timezone' => 'Africa/Sao_Tome'],
            ['name' => 'Saudi Arabia', 'timezone' => 'Asia/Riyadh'],
            ['name' => 'Senegal', 'timezone' => 'Africa/Dakar'],
            ['name' => 'Serbia', 'timezone' => 'Europe/Belgrade'],
            ['name' => 'Seychelles', 'timezone' => 'Indian/Mahe'],
            ['name' => 'Sierra Leone', 'timezone' => 'Africa/Freetown'],
            ['name' => 'Singapore', 'timezone' => 'Asia/Singapore'],
            ['name' => 'Sint Maarten (Dutch part)', 'timezone' => 'America/Sint_Maarten'],
            ['name' => 'Slovakia (Slovak Republic)', 'timezone' => 'Europe/Bratislava'],
            ['name' => 'Slovenia', 'timezone' => 'Europe/Ljubljana'],
            ['name' => 'Solomon Islands', 'timezone' => 'Pacific/Guadalcanal'],
            ['name' => 'Somalia', 'timezone' => 'Africa/Mogadishu'],
            ['name' => 'South Africa', 'timezone' => 'Africa/Johannesburg'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'timezone' => 'Atlantic/South_Georgia'],
            ['name' => 'South Sudan', 'timezone' => 'Africa/Juba'],
            ['name' => 'Spain', 'timezone' => 'Europe/Madrid'],
            ['name' => 'Sri Lanka', 'timezone' => 'Asia/Colombo'],
            ['name' => 'Sudan', 'timezone' => 'Africa/Khartoum'],
            ['name' => 'Suriname', 'timezone' => 'America/Paramaribo'],
            ['name' => 'Svalbard and Jan Mayen Islands', 'timezone' => 'Arctic/Longyearbyen'],
            ['name' => 'Swaziland', 'timezone' => 'Africa/Mbabane'],
            ['name' => 'Sweden', 'timezone' => 'Europe/Stockholm'],
            ['name' => 'Switzerland', 'timezone' => 'Europe/Zurich'],
            ['name' => 'Syrian Arab Republic', 'timezone' => 'Asia/Damascus'],
            ['name' => 'Taiwan', 'timezone' => 'Asia/Taipei'],
            ['name' => 'Tajikistan', 'timezone' => 'Asia/Dushanbe'],
            ['name' => 'Tanzania (United Republic of)', 'timezone' => 'Africa/Dar_es_Salaam'],
            ['name' => 'Thailand', 'timezone' => 'Asia/Bangkok'],
            ['name' => 'Togo', 'timezone' => 'Africa/Lome'],
            ['name' => 'Tokelau', 'timezone' => 'Pacific/Fakaofo'],
            ['name' => 'Tonga', 'timezone' => 'Pacific/Tongatapu'],
            ['name' => 'Trinidad and Tobago', 'timezone' => 'America/Port_of_Spain'],
            ['name' => 'Tunisia', 'timezone' => 'Africa/Tunis'],
            ['name' => 'Turkey', 'timezone' => 'Europe/Istanbul'],
            ['name' => 'Turkmenistan', 'timezone' => 'Asia/Ashgabat'],
            ['name' => 'Tuvalu', 'timezone' => 'Pacific/Funafuti'],
            ['name' => 'Uganda', 'timezone' => 'Africa/Kampala'],
            ['name' => 'Ukraine', 'timezone' => 'Europe/Kiev'],
            ['name' => 'United Arab Emirates', 'timezone' => 'Asia/Dubai'],
            ['name' => 'United Kingdom', 'timezone' => 'Europe/London'],
            ['name' => 'United States Minor Outlying Islands', 'timezone' => 'Pacific/Wake'],
            ['name' => 'Uruguay', 'timezone' => 'America/Montevideo'],
            ['name' => 'Uzbekistan', 'timezone' => 'Asia/Tashkent'],
            ['name' => 'Vanuatu', 'timezone' => 'Pacific/Efate'],
            ['name' => 'Venezuela (Bolivarian Republic of)', 'timezone' => 'America/Caracas'],
            ['name' => 'Viet Nam', 'timezone' => 'Asia/Ho_Chi_Minh'],
            ['name' => 'Western Sahara', 'timezone' => 'Africa/El_Aaiun'],
            ['name' => 'Yemen', 'timezone' => 'Asia/Aden'],
            ['name' => 'Zambia', 'timezone' => 'Africa/Lusaka'],
            ['name' => 'Zimbabwe', 'timezone' => 'Africa/Harare']
        ];
		DB::table('countries')->insert($countries);
    }
}
