<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuRoleTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('menu_role')->delete();

        \DB::table('menu_role')->insert([
            
            [
                'id' => 42,
                'menu_id' => 1,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 43,
                'menu_id' => 2,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
           
            [
                'id' => 44,
                'menu_id' => 3,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 45,
                'menu_id' => 4,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 46,
                'menu_id' => 5,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 47,
                'menu_id' => 6,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 48,
                'menu_id' => 7,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 49,
                'menu_id' => 8,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 50,
                'menu_id' => 9,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 51,
                'menu_id' => 10,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 52,
                'menu_id' => 11,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 53,
                'menu_id' => 12,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 54,
                'menu_id' => 13,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 55,
                'menu_id' => 14,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 56,
                'menu_id' => 15,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 57,
                'menu_id' => 16,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 58,
                'menu_id' => 17,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 59,
                'menu_id' => 18,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 60,
                'menu_id' => 19,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 61,
                'menu_id' => 20,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 62,
                'menu_id' => 21,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 63,
                'menu_id' => 22,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 64,
                'menu_id' => 23,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 65,
                'menu_id' => 24,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 66,
                'menu_id' => 25,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 67,
                'menu_id' => 26,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 68,
                'menu_id' => 27,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 69,
                'menu_id' => 28,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 72,
                'menu_id' => 31,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 73,
                'menu_id' => 32,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 74,
                'menu_id' => 33,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 75,
                'menu_id' => 34,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 76,
                'menu_id' => 35,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            // [
            //     'id' => 77,
            //     'menu_id' => 36,
            //     'role_id' => 1,
            //     'can_create' => 1,
            //     'can_read' => 1,
            //     'can_update' => 1,
            //     'can_delete' => 1,
            //     'created_at' => '2025-02-03 15:07:08',
            //     'updated_at' => '2025-02-03 15:07:08',
            // ],
            [
                'id' => 78,
                'menu_id' => 37,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 79,
                'menu_id' => 38,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 80,
                'menu_id' => 39,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 81,
                'menu_id' => 40,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 82,
                'menu_id' => 41,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 83,
                'menu_id' => 42,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 84,
                'menu_id' => 43,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 85,
                'menu_id' => 44,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 86,
                'menu_id' => 45,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 87,
                'menu_id' => 46,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 88,
                'menu_id' => 47,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 89,
                'menu_id' => 48,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 90,
                'menu_id' => 49,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 91,
                'menu_id' => 50,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 92,
                'menu_id' => 51,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 93,
                'menu_id' => 52,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 94,
                'menu_id' => 53,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 95,
                'menu_id' => 54,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 96,
                'menu_id' => 29,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 97,
                'menu_id' => 30,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 98,
                'menu_id' => 57,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 99,
                'menu_id' => 58,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 100,
                'menu_id' => 59,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 101,
                'menu_id' => 60,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 102,
                'menu_id' => 61,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 103,
                'menu_id' => 63,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 104,
                'menu_id' => 64,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 105,
                'menu_id' => 62,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 106,
                'menu_id' => 65,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 107,
                'menu_id' => 66,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 108,
                'menu_id' => 67,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 109,
                'menu_id' => 68,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
            [
                'id' => 110,
                'menu_id' => 69,
                'role_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_at' => '2025-02-03 15:07:08',
                'updated_at' => '2025-02-03 15:07:08',
            ],
        ]);

    }
}
