version: "1.1"
services:
  app:
    build:
      args:
        user: vishnu
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: hrjee-v2-php
    container_name: hrjee-v2-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - hrjee_network

  database:
    image: mysql:8.0
    container_name: hrjee-v2-db
    restart: unless-stopped
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - hrjee_network

  nginx:
    image: nginx:1.17-alpine
    container_name: hrjee-v2-nginx
    restart: unless-stopped
    ports:
      - 9000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - hrjee_network
  
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    restart: always
    ports:
      - 8050:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - hrjee_network
  
networks:
  hrjee_network:
    driver: bridge